1-module
js-tasks-ru/jsbasic-20210225_dyachenkoandrii pull request #2
Opened 2021-03-11 19:46 UTC by Trikita73

2021-03-11 19:46 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-12 15:03 UTC, SinimaWath requested changes

2021-03-12 15:03 UTC, SinimaWath commented on 1-module/1-task/index.js
> +          return n * factorial(n - x);
Круто, что знаешь рекурсию, но давай в этой задаче без нее :)

2021-03-12 15:03 UTC, SinimaWath commented on 1-module/1-task/index.js
> +          return 1;
Эту проверку стоит сделать еще до цикла. Так ты уменьшишь вложенность

2021-03-12 15:03 UTC, SinimaWath commented on 1-module/1-task/index.js
> +	let x = 1;
Название переменной не говорящее, другой разработчик не поймет, зачем она нужна:
переменная должна говорить:
- Что она хранит
- Для чего хранит

`x` - явно ничего не говорит про factorial.

2021-03-12 15:03 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
1. Тебе нужна еще проверка на null
2. И проверить, пробелы через **includes** - функцию

2021-03-12 15:03 UTC, SinimaWath commented on 1-module/4-task/index.js
> +// checkSpam('1XbeT now')) === true;
Это лишнее стоит убрать

2021-03-12 15:03 UTC, SinimaWath commented on 1-module/5-task/index.js
> +	}
1. - else тут лишняя, так как в if у тебя уже есть return, и дальше код не будет выполняться

2021-03-14 23:49 UTC, Trikita73 commented on 1-module/4-task/index.js
> +// checkSpam('1XbeT now')) === true;
ок.

2021-03-14 23:49 UTC, Trikita73 commented on 1-module/5-task/index.js
> +	}
Исправил:)

2021-03-14 23:50 UTC, Trikita73 commented on 1-module/2-task/index.js
> +  }
Возможно я что-то делаю неправильно! Мне нужна ваша помощь здесь... Пример скинул

2021-03-14 23:50 UTC, Trikita73 commented on 1-module/1-task/index.js
> +	let x = 1;
Исправил

2021-03-14 23:51 UTC, Trikita73 commented on 1-module/1-task/index.js
> +          return 1;
ок

2021-03-14 23:51 UTC, Trikita73 commented on 1-module/1-task/index.js
> +          return n * factorial(n - x);
Попробую) Пример скинул!

2021-03-15 13:42 UTC, SinimaWath requested changes

2021-03-15 13:42 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    */
Давай уберем старый пример :)

2021-03-15 13:42 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
У тебя все ок. Только проблемы с порядком.

Нужно сначало проверить `name == null`, потому что `null.length < 4` это ошибка

И давай упростим до одной строки, когда условий мало, так можно сделать:
`return !(name == null || name.length < 4 ....`

2021-03-15 13:42 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    }
1 - Тут else лишний
2 - Надо проверить еще на NaN, Infifinity, -Infinity

2021-03-15 13:42 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Отписал

2021-03-15 16:51 UTC, Trikita73 commented on 1-module/2-task/index.js
> +  }
Круть:)

2021-03-15 16:51 UTC, Trikita73 commented on 2-module/1-task/index.js
> +    }
ок

2021-03-16 18:48 UTC, SinimaWath requested changes

2021-03-16 18:48 UTC, SinimaWath commented on 2-module/3-task/index.js
> +}
У тебя не проходят тесты на эту задачу. 

По-условию задачи, функция read - принимает 2 аргумента: `read(a, b)`

2021-03-17 20:19 UTC, Trikita73 commented on 2-module/3-task/index.js
> +}
Исправил)

2021-03-17 21:16 UTC, SinimaWath approved these changes

2021-03-17 21:17 UTC, merged