4-module
js-tasks-ru/jsbasic-20210225_dyachenkoandrii pull request #4
Opened 2021-04-08 23:28 UTC by Trikita73

Нужна ваша помощь! В этих двух задачах я не могу понять где у меня ошибки, помогите пожалуйста...

2021-04-12 19:34 UTC, SinimaWath requested changes

2021-04-12 19:34 UTC, SinimaWath commented on 4-module/1-task/index.js
> +      li.appendChild(document.createTextNode(`${item.firstName}, ${item.lastName}`));
Давай перепишем на insertAdjacentHTML.
- Формируем шаблон
- Вставляем в ul

2021-04-12 19:34 UTC, SinimaWath commented on 4-module/1-task/index.js
> +    document.body.appendChild(ul);
По условию задачи не нужно вставлять елемент в DOM.

Нужно просто чтобы функция возвращался готовый DOM елемент

2021-04-14 23:02 UTC, Trikita73 commented on 4-module/1-task/index.js
> +      li.appendChild(document.createTextNode(`${item.firstName}, ${item.lastName}`));
Попробовал так и сделать, только не могу понять как сделать так чтоб - число элементов в списке и число объектов в массиве должны быть одинаковым, нужна ваша помощь.

2021-04-14 23:05 UTC, Trikita73 commented
В 3-м задании, не получается...

2021-04-15 19:28 UTC, SinimaWath commented on 4-module/1-task/index.js
> +	  ul.insertAdjacentHTML('beforeEnd', 'li');
Нужно использовать forEach.

- у тебя есть friends
- Нужно обойти весь массив
- Создать шаблон на каждый елемент
- Вставить этот шаблон через insertAdjacentHTML

2021-04-15 19:28 UTC, SinimaWath commented on 4-module/3-task/index.js
> +        }
Надо еще учесть другие случаи, которые описаны в задаче

2021-04-18 23:04 UTC, Trikita73 commented on 4-module/1-task/index.js
> +	  ul.insertAdjacentHTML('beforeEnd', 'li');
Исправил

2021-04-18 23:09 UTC, Trikita73 commented on 4-module/3-task/index.js
> +        }
Сделал, но задача не проходит проверку

2021-05-17 22:05 UTC, closed without merging